---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.150.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: hellux/jotdown@0.3.2
- name: evilmartians/lefthook@v1.6.5
- name: watchexec/watchexec@v1.25.1
